apiVersion: v1
kind: Service
metadata:
  name: donet-demo
  namespace: aks-demo
spec:
  type: LoadBalancer
  selector:
    app: donet-demo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000